### ISSUE TITLE
useless exception on parse error

### ISSUE THREAD

**Issue by georgefx** [mcmtroffaes/sphinxcontrib-bibtex#104]
# Problem

 sphinxcontrib-bibtex does not provide any useful error message when it encounters a parse error in a bibtex file.
1. It is not clear from the exception that the problem actually is a parse error in the bibtex file.
2. No line number or other subsequent information is given on what's actually wrong with the bibtex file.

An example is the stack trace below. Would it be possible to print some more detailed information in case of a parse error?

As a workaround I was able to use `pybtex-format` to find the problem in my file.

```
parsing bibtex file $HOME/somefile.bib... 
Exception occurred:
Traceback (most recent call last):
  File "$HOME/miniconda3/envs/sphinx-doc/bin/sphinx-build", line 6, in <module>
    sys.exit(sphinx.main())
  File "$HOME/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "$HOME/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/__init__.py", line 92, in build_main
    return cmdline.main(argv)
  File "$HOME/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/cmdline.py", line 283, in main
    print(format_exception_cut_frames().rstrip(), file=error)
  File "$HOME/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/util/__init__.py", line 480, in format_exception_cut_frames
    res += traceback.format_exception_only(typ, val)
  File "$HOME/miniconda3/envs/sphinx-doc/lib/python3.5/traceback.py", line 136, in format_exception_only
    return list(TracebackException(etype, value, None).format_exception_only())
  File "$HOME/miniconda3/envs/sphinx-doc/lib/python3.5/traceback.py", line 439, in __init__
    _seen.add(exc_value)
TypeError: unhashable type: 'TokenRequired'
```
# Version info

miniconda on Ubuntu Linux 16.04.1 LTS x86_64

```
# packages in environment at $HOME/miniconda3/envs/sphinx-doc:
#
alabaster                 0.7.8                    py35_0  
alabaster                 0.7.9                     <pip>
babel                     2.3.3                    py35_0  
Babel                     2.3.4                     <pip>
docutils                  0.12                     py35_2  
imagesize                 0.7.1                    py35_0  
jinja2                    2.8                      py35_1  
latexcodec                1.0.3                     <pip>
markupsafe                0.23                     py35_2  
openssl                   1.0.2h                        1  
oset                      0.1.3                     <pip>
pip                       8.1.2                    py35_0  
pybtex                    0.20.1                    <pip>
pybtex-docutils           0.2.1                     <pip>
pygments                  2.1.3                    py35_0  
python                    3.5.2                         0  
pytz                      2016.6.1                 py35_0  
PyYAML                    3.11                      <pip>
readline                  6.2                           2  
setuptools                23.0.0                   py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sphinx                    1.4.1                    py35_0  
sphinx_rtd_theme          0.1.9                    py35_0  
sphinxcontrib-bibtex      0.3.4                     <pip>
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
zlib                      1.2.8                         3  
```

**Comment by mcmtroffaes** [comment]
Hmm... strange. I'll need to have a look at how pybtex-format propagates errors. It's indeed annoying that sphinx doesn't seem to catch this in a better way.

**Comment by mcmtroffaes** [comment]
I can't reproduce this: I created a badly formatted bib file and got a sensible message. I suspect it's a bug or "feature" of pybtex or sphinx failing somehow to propagate the exception properly in a corner case that your bib file triggered. Can you share the bib file that produced your error so I can reproduce locally?

**Comment by georgefx** [comment]
I attached a minimal example that reproduces the problem: [buggy-sphinx-bibtex-01.tar.gz](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/files/486816/buggy-sphinx-bibtex-01.tar.gz)

```
buggy-sphinx-bibtex% make
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.1
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
checking for /auto-home/staff/altmann/stuff/buggy-sphinx-bibtex/source/buggy.bib in bibtex cache... not found                                                   
parsing bibtex file /auto-home/staff/altmann/stuff/buggy-sphinx-bibtex/source/buggy.bib... 
Exception occurred:
Traceback (most recent call last):
  File "/home/staff/altmann/miniconda3/envs/sphinx-doc/bin/sphinx-build", line 6, in <module>
    sys.exit(sphinx.main())
  File "/home/staff/altmann/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/home/staff/altmann/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/__init__.py", line 92, in build_main
    return cmdline.main(argv)
  File "/home/staff/altmann/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/cmdline.py", line 283, in main
    print(format_exception_cut_frames().rstrip(), file=error)
  File "/home/staff/altmann/miniconda3/envs/sphinx-doc/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg/sphinx/util/__init__.py", line 480, in format_exception_cut_frames
    res += traceback.format_exception_only(typ, val)
  File "/home/staff/altmann/miniconda3/envs/sphinx-doc/lib/python3.5/traceback.py", line 136, in format_exception_only
    return list(TracebackException(etype, value, None).format_exception_only())
  File "/home/staff/altmann/miniconda3/envs/sphinx-doc/lib/python3.5/traceback.py", line 439, in __init__
    _seen.add(exc_value)
TypeError: unhashable type: 'InvalidNameString'
Makefile:81: recipe for target 'html' failed
make: *** [html] Error 1
```

Thanks for looking into this!

**Comment by georgefx** [comment]
Just updated to latest sphinx 1.4.6, didn't help, same exception traceback...


```
% conda list 
# packages in environment at /home/staff/altmann/miniconda3/envs/sphinx-doc:
#
alabaster                 0.7.9                     <pip>
alabaster                 0.7.9                    py35_0  
Babel                     2.3.4                     <pip>
babel                     2.3.4                    py35_0  
docutils                  0.12                     py35_2  
imagesize                 0.7.1                    py35_0  
jinja2                    2.8                      py35_1  
latexcodec                1.0.3                     <pip>
markupsafe                0.23                     py35_2  
openssl                   1.0.2h                        1  
oset                      0.1.3                     <pip>
pip                       8.1.2                    py35_0  
pybtex                    0.20.1                    <pip>
pybtex-docutils           0.2.1                     <pip>
pygments                  2.1.3                    py35_0  
python                    3.5.2                         0  
pytz                      2016.6.1                 py35_0  
PyYAML                    3.11                      <pip>
readline                  6.2                           2  
setuptools                27.2.0                   py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sphinx                    1.4.6                    py35_0  
sphinx_rtd_theme          0.1.9                    py35_0  
sphinxcontrib-bibtex      0.3.4                     <pip>
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
zlib                      1.2.8                         3  
```

**Comment by mcmtroffaes** [comment]
Thanks for the file.

Done a quick test, I still can't reproduce this. Here's what I see, with Sphinx 1.4.6 and pybtex 0.20.1 (same as yours):

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.6
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
checking for .../buggy-sphinx-bibtex/source/buggy.bib in bibtex cache... not found
parsing bibtex file .../buggy-sphinx-bibtex/source/buggy.bib... 
Exception occurred:
  File ".../python2.7/site-packages/pybtex/errors.py", line 76, in report_error
    raise exception
InvalidNameString: Too many commas in u'Georg Lucas,,,,,,,,,'
The full traceback has been saved in /tmp/sphinx-err-Dyc4TY.log, if you want to report the issue to the developers.
```

This is on Python 2.7. I'll test with Python 3.5 later, I hope that will tease it out.

**Comment by georgefx** [comment]
Yep, same here with python 2. Seems to be a python 3 issue...

**Comment by gm6** [comment]
Here, Python3.5
`Exception occurred:
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/sphinx/__init__.py", line 47, in main
    sys.exit(build_main(argv))
  File "/usr/lib/python3.5/site-packages/sphinx/__init__.py", line 87, in build_main
    return cmdline.main(argv)
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 285, in main
    print(format_exception_cut_frames().rstrip(), file=error)
  File "/usr/lib/python3.5/site-packages/sphinx/util/__init__.py", line 407, in format_exception_cut_frames
    res += traceback.format_exception_only(typ, val)
  File "/usr/lib/python3.5/traceback.py", line 136, in format_exception_only
    return list(TracebackException(etype, value, None).format_exception_only())
  File "/usr/lib/python3.5/traceback.py", line 439, in __init__
    _seen.add(exc_value)
TypeError: unhashable type: 'PluginNotFound'`
So is it because sphinxcontrib-bibtex doesn't work with python3?

**Comment by georgefx** [comment]
@gm6 the error reported by sphinx is confusing, but it probably wants to tell you it didn't find `sphinxcontrib-bibtex` or some other plugin. `sphinxcontrib-bibtex` does work with python 3.

**Comment by gm6** [comment]
Hi man, seriously? Thumb down? I was just asking for help, not offending anybody.

**Comment by georgefx** [comment]
No offense taken nor intended. You reported a problem that is not related to the original problem in any way. Thumbs down for hijacking the bug. Check http://groups.google.com/group/sphinx-users for help on sphinx and plugins.

**Comment by gm6** [comment]
Hey man, that is a question, not an affirmative sentense

**Comment by mcmtroffaes** [comment]
@georgefx I just tested your example again with Python 2 and 3, error messages are sensible, e.g. on Python 3:

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.5.5
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
checking for /extra/tmp/dma0mt/badbib/buggy-sphinx-bibtex/source/buggy.bib in bibtex cache... not found
parsing bibtex file /extra/tmp/dma0mt/badbib/buggy-sphinx-bibtex/source/buggy.bib... 
Exception occurred:
  File "/home/stats/dma0mt/extra/pyvenv3-sphinxcontrib-bibtex/lib/python3.5/site-packages/pybtex/errors.py", line 77, in report_error
    raise exception
pybtex.database.InvalidNameString: Too many commas in 'Georg Lucas,,,,,,,,,'
```

I'm sorry but I'm afraid there's not much else I can do to help since I cannot reproduce your problem locally...

@gm6 That's an unrelated problem (looks like an installation problem).

**Comment by georgefx** [comment]
@mcmtroffaes Thanks for coming back to this. I can confirm that sphinx with  python 2 and python 3 give the above error message on arch linux. For python 3:

* Sphinx (1.5.5)
* sphinx-rtd-theme (0.2.4)
* sphinxcontrib-bibtex (0.3.5)

Looks like the problem was fixed in sphinx.

**Comment by mcmtroffaes** [comment]
Ok, thanks for confirming!
