### ISSUE TITLE
not building .html using readthedocs.org

### ISSUE THREAD

**Issue by huckl3b3rry87** [mcmtroffaes/sphinxcontrib-bibtex#107]
My html is able to build just fine until I try to use readthedocs.org to do it and I get:
```
 Build failed
python -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/.cache/pip sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1
cat conf.py
python /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
ExtensionError: Could not import extension sphinxcontrib.bibtex (exception: No module named sphinxcontrib.bibtex)

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named sphinxcontrib.bibtex)
```
After getting this error, I tried to update the Requirements file options under advanced settings as:
```
pip install -r require.txt
```
where require.txt simply contains:
```
pip install sphinxcontrib-bibtex
```
but then I get another error.  
```
Build failed
python3 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/.cache/pip sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1
python /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/nloptcontroljl/.cache/pip -rpip install -r require.txt
Could not open requirements file: [Errno 2] No such file or directory: 'pip install -r require.txt'
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Command time: 0s Return: 1
```
the file require.txt was placed in my main directory in my project so, I am not sure where it is looking or why it cannot find this file.

Any thoughts?

**Comment by huckl3b3rry87** [comment]
the issue was that I put:
```
pip install -r require.txt
```
into the Requirements file box instead of 
```
require.txt
```
more on this for the interested is here
https://github.com/huckl3b3rry87/NLOptControl.jl/issues/2

**Comment by mcmtroffaes** [comment]
Sorry for the delay in responding here - but I'm glad you figured it out!

**Comment by ofloveandhate** [comment]
that last issue link is dead

**Comment by ShiqiHe000** [comment]
Hi @huckl3b3rry87! 
I build my HTML locally and it works fine, but when I uploaded to GitHub, Readthedocs fails to build it. I encountered the same issue. Could you give me more details about how you solve this problem? I am not sure what the Requirements file box is and where is the advance setting? Thank you!

**Comment by ShiqiHe000** [comment]
@huckl3b3rry87 No worries. I solved my problem.
If there is anyone have the same issue as I do, you could find out more in here:
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/sphinx-config.html

**Comment by KrOstir** [comment]
> @huckl3b3rry87 No worries. I solved my problem.
> If there is anyone have the same issue as I do, you could find out more in here:
> https://sphinx-rtd-tutorial.readthedocs.io/en/latest/sphinx-config.html

Can you explain what you did? I am struggling with the same problem.
