### ISSUE TITLE
plugin pybtex.backends.docutils not found

### ISSUE THREAD

**Issue by girardinsamuel** [mcmtroffaes/sphinxcontrib-bibtex#109]
When building a doc with Sphinx with plugin sphinxcontrib-bibtex, I got this error _plugin pybtex.backends.docutils not found_. But sphinxcontrib-bibtex is installed and the doc can be build on a Windows computer.

The information on the platform:
# Ubuntu 12.04
# Python 2.7

Here the log file:
# Sphinx version: 1.4.8
# Python version: 2.7.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 163, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 473, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/bibtex/__init__.py", line 18, in <module>
    from sphinxcontrib.bibtex.roles import CiteRole
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/bibtex/roles.py", line 16, in <module>
    class CiteRole(XRefRole):
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/bibtex/roles.py", line 19, in CiteRole
    backend = find_plugin('pybtex.backends', 'docutils')()
  File "/usr/local/lib/python2.7/dist-packages/pybtex/plugin/__init__.py", line 105, in find_plugin
    return _load_entry_point(plugin_group, name, use_aliases=True)
  File "/usr/local/lib/python2.7/dist-packages/pybtex/plugin/__init__.py", line 80, in _load_entry_point
    raise PluginNotFound(group, name)
PluginNotFound: plugin pybtex.backends.docutils not found

**Comment by mcmtroffaes** [comment]
You also need this extension: https://pypi.python.org/pypi/pybtex-docutils/

**Comment by girardinsamuel** [comment]
the pip freeze command output:
pybtex-docutils==0.2.1
So I got this extension installed.

**Comment by mcmtroffaes** [comment]
Weird. It does look like a problem with your environment rather than a bug. Have you tried running from a virtual environment? That's the best way to ensure that you have everything properly installed. For example, it can be possible that pip shows you dependencies for an environment that's different from the one from your sphinx invocation. Here's a good reference:

https://packaging.python.org/installing/#creating-virtual-environments

**Comment by girardinsamuel** [comment]
I have tried yes and now it's working ! 
Thank you

**Comment by mcmtroffaes** [comment]
Great - glad I could help.
