### ISSUE TITLE
EOFError raised in test_issue80_parallel with Python 3.5

### ISSUE THREAD

**Issue by ghisvail** [mcmtroffaes/sphinxcontrib-bibtex#122]
Fails with Python 3.5, passes with Python 3.6. Tested on Debian unstable.
```
======================================================================
ERROR: test_issue80_parallel.test_issue80_parallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 142, in decorator
    func(*(args + (app, status, warning)), **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_issue80_parallel.py", line 20, in test_issue80_parallel
    app.builder.build_all()
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 211, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 358, in write
    nproc=self.app.parallel - 1)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 402, in _write_parallel
    tasks.add_task(write_process, arg, add_warnings)
  File "/usr/lib/python3/dist-packages/sphinx/util/parallel.py", line 89, in add_task
    self._join_one()
  File "/usr/lib/python3/dist-packages/sphinx/util/parallel.py", line 98, in _join_one
    exc, result = pipe.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by mcmtroffaes** [comment]
Can't reproduce on travis or locally so far. But we could disable the test, it's not really doing much besides checking that parallel builds are disabled. From the error message it looks like it actually tries to do a parallel build - that would be very odd...

**Comment by ghisvail** [comment]
And it fails only on Python 3.5. You might want to get rid of this test considering its fragility.
