### ISSUE TITLE
AttributeError: type object 'Theme' has no attribute 'themes'

### ISSUE THREAD

**Issue by ghisvail** [mcmtroffaes/sphinxcontrib-bibtex#126]
Using the latest released version `0.3.6`, the test log is riddled with `AttributeError`:

```
python3.6 -m nose --ignore-files=test_issue1
EEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_bibfile_out_of_date.test_bibfile_out_of_date
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_bibfilenotfound.test_bibfilenotfound
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_citationnotfound.test_citationnotfound
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_crossref.test_crossref
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_custom_style.test_custom_style
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_filter.test_filter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_filter_fix_author_keyerror.test_filter_fix_author_keyerror
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_filter_option_clash.test_filter_option_clash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_filter_syntax_error.test_filter_syntax_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_invalid_cite_option.test_invalid_cite_option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue2.test_mixing_citation_styles
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue4.test_encoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue61.test_multiple_keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue62.test_local_bibliographies
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue77.test_issue77
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue85.test_issue77
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue87.test_issue87
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_issue91.test_issue91
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_latex_refs.test_latex_refs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_list_bullet.test_list_bullet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_list_citation.test_list_citation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_list_enumerated.test_list_enumerated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_list_invalid.test_list_invalid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

======================================================================
ERROR: test_sphinx.test_sphinx
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 151, in decorator
    app.cleanup()
  File "/usr/lib/python3/dist-packages/sphinx_testing/util.py", line 96, in cleanup
    Theme.themes.clear()
AttributeError: type object 'Theme' has no attribute 'themes'

----------------------------------------------------------------------
Ran 24 tests in 5.775s

FAILED (errors=24)
```

Am I missing something here?

**Comment by mcmtroffaes** [comment]
Looks like a bug in the sphinx_testing module.

**Comment by mcmtroffaes** [comment]
See https://github.com/sphinx-doc/sphinx-testing/blame/master/src/sphinx_testing/util.py#L93 - I guess you're using Sphinx < 1.6 with non-latest version of sphinx_testing. If that's the case, upgrading to the latest version of sphinx_testing might fix the problem.

**Comment by mcmtroffaes** [comment]
Correction: I guess you're using Sphinx >= 1.6 with an older version of sphinx_testing. "themes" appears to have been removed with Sphinx 1.6.

**Comment by ghisvail** [comment]
> I guess you're using Sphinx >= 1.6

Correct.

> "themes" appears to have been removed with Sphinx 1.6.

So the error is because our version of `sphinx-testing` is too old?

**Comment by ghisvail** [comment]
Answering my own question: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875399

**Comment by mcmtroffaes** [comment]
Great. :-)
