### ISSUE TITLE
Most tests fail with `Unknown node: bibliography`

### ISSUE THREAD

**Issue by zorun** [mcmtroffaes/sphinxcontrib-bibtex#135]
On Arch Linux, almost all tests fail, with both python2 and python3:

```
======================================================================
ERROR: test_list_bullet.test_list_bullet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3.6/site-packages/sphinx_testing/util.py", line 143, in decorator
    func(*(args + (app, status, warning)), **kwargs)
  File "/build/python-sphinxcontrib-bibtex/src/sphinxcontrib-bibtex-0.3.6/test/test_list_bullet.py", line 22, in test_list_bullet
    app.builder.build_all()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 295, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 399, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 436, in write
    self._write_serial(sorted(docnames))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 445, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/html.py", line 602, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python3.6/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.6/site-packages/sphinx/writers/html.py", line 56, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.6/site-packages/sphinx/writers/html.py", line 882, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: bibliography
```

There are also some Sphinx warnings triggering failures:
```
======================================================================
ERROR: test_latex_refs.test_latex_refs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3.6/site-packages/sphinx_testing/util.py", line 143, in decorator
    func(*(args + (app, status, warning)), **kwargs)
  File "/build/python-sphinxcontrib-bibtex/src/sphinxcontrib-bibtex-0.3.6/test/test_latex_refs.py", line 21, in test_latex_refs
    app.builder.build_all()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 295, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 399, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/latex.py", line 145, in write
    appendices=((docclass != 'howto') and self.config.latex_appendices or []))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/latex.py", line 195, in assemble_doctree
    self.env.resolve_references(largetree, indexfile, self)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 847, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 860, in apply_post_transforms
    transformer.apply_transforms()
  File "/usr/lib/python3.6/site-packages/sphinx/transforms/__init__.py", line 96, in apply_transforms
    Transformer.apply_transforms(self)
  File "/usr/lib/python3.6/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.6/site-packages/sphinx/transforms/post_transforms/__init__.py", line 101, in apply
    self.warn_missing_reference(refdoc, typ, target, node, domain)
  File "/usr/lib/python3.6/site-packages/sphinx/transforms/post_transforms/__init__.py", line 177, in warn_missing_reference
    location=node, type='ref', subtype=typ)
  File "/usr/lib/python3.6/logging/__init__.py", line 1640, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sphinx/util/logging.py", line 112, in log
    super(SphinxLoggerAdapter, self).log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1672, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1372, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 859, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 718, in filter
    result = f.filter(record)
  File "/usr/lib/python3.6/site-packages/sphinx/util/logging.py", line 380, in filter
    raise SphinxWarning(location + ":" + message)
sphinx.errors.SphinxWarning: /build/python-sphinxcontrib-bibtex/src/sphinxcontrib-bibtex-0.3.6/test/latex_refs/contents.rst:4:citation not found: 1657:huygens
```

System:

- Arch Linux
- python 2.7.14 and 3.6.4
- sphinx 1.7.2
- pybtex 0.21
- pybtex-docutils 0.2.1

**Comment by mcmtroffaes** [comment]
Fixed in develop. I'll push a release soon.

**Comment by zorun** [comment]
Thanks, all those tests now pass with 0.4.0!

**Comment by mcmtroffaes** [comment]
Great - thanks for confirming! ^^
