### ISSUE TITLE
Tests are failing with Sphinx 1.8

### ISSUE THREAD

**Issue by mitya57** [mcmtroffaes/sphinxcontrib-bibtex#149]
```
======================================================================
ERROR: test_issue1.test_tinker
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx_testing/util.py", line 159, in decorator
    app = TestApp(*self.sphinxargs, **sphinxkwargs)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx_testing/util.py", line 97, in __init__
    verbosity, parallel)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx/registry.py", line 483, in load_extension
    metadata = mod.setup(app)
  File "/home/dmitry/.local/lib/python3.6/site-packages/tinkerer/ext/blog.py", line 126, in setup
    app.add_config_value("author", "Winston Smith", True)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx/application.py", line 568, in add_config_value
    self.config.add(name, default, rebuild, types)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx/config.py", line 319, in add
    raise ExtensionError(__('Config value %r already present') % name)
sphinx.errors.ExtensionError: Config value 'author' already present

======================================================================
FAIL: test_latex_refs.test_latex_refs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dmitry/.local/lib/python3.6/site-packages/sphinx_testing/util.py", line 162, in decorator
    func(*(args + (app, status, warning)), **kwargs)
  File "/home/dmitry/upstream/sphinxcontrib-bibtex/test/test_latex_refs.py", line 24, in test_latex_refs
    '\\\\hyperref\[(\\\\detokenize{)?contents:huygens(})?\]', output)
AssertionError
```

**Comment by mitya57** [comment]
With some bugs fixed in sphinx-testing, we are down to just 2 failed tests. I have updated the bug description accordingly.
