### ISSUE TITLE
Build failed when using readthedoc.org

### ISSUE THREAD

**Issue by ShiqiHe000** [mcmtroffaes/sphinxcontrib-bibtex#191]
Hi! I install `sphinxcontrib-bibtex` locally and build html successfully. 

The `extensions` in my `conf.py` looks like this:
```
extensions = ['sphinx.ext.githubpages',  'recommonmark', 'sphinx.ext.mathjax',                   
'sphinx.ext.intersphinx', 'sphinxcontrib.bibtex']

```

However, when I uploaded my `sphinx project` to GitHub and use `readthedoc.org`  to auto-build my html page, it fails. 

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/2d-advection/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinxcontrib.bibtex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/2d-advection/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/2d-advection/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/2d-advection/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/2d-advection/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')
```

What should I do? Thank you!

**Comment by ShiqiHe000** [comment]
I figured out my issue!
So you need to tell Readthedocs to install `sphinxcontrib-bibtex`. 
*  You need a requirements.txt in your root directory
   -  onyl put `sphinxcontrib-bibtex` in the requirement file
*  You need to change the ***Advance setting*** in Readthedocs. 
    -  There is a blank for you to fill in the requirement file name

**Comment by mcmtroffaes** [comment]
Glad you figured it out!
