### ISSUE TITLE
Entries of type @dataset cause an error

### ISSUE THREAD

**Issue by uellue** [mcmtroffaes/sphinxcontrib-bibtex#195]
When citing an entry of type `@dataset`, the following error occurs with sphinxcontrib-bibtex==1.0.0 (latest):

```
# Sphinx version: 3.0.0
# Python version: 3.7.4 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   reading sources... [ 56%] citing
#   reading sources... [ 57%] concepts
#   reading sources... [ 58%] contributing
#   reading sources... [ 60%] debugging
#   reading sources... [ 61%] dist_tests
#   reading sources... [ 63%] formats
#   reading sources... [ 64%] gsoc
#   reading sources... [ 65%] index
#   checking for C:\Users\weber\Documents\LiberTEM\LiberTEM\docs\source\references-libertem.bib in bibtex cache...
#   up to date
# Loaded extensions:
#   sphinx.ext.mathjax (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.1) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.2) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\users\weber\.conda\envs\libertem\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc.type_comment (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\autodoc\type_comment.py
#   sphinx.ext.autodoc (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.todo (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.viewcode (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\viewcode.py
#   sphinx.ext.githubpages (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\githubpages.py
#   sphinx.ext.napoleon (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\napoleon\__init__.py
#   sphinx.ext.intersphinx (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx.ext.doctest (3.0.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\ext\doctest.py
#   sphinxcontrib.bibtex (unknown version) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinxcontrib\bibtex\__init__.py
#   nbsphinx (0.6.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\nbsphinx.py
#   nbsphinx_link (1.3.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\nbsphinx_link\__init__.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from c:\users\weber\.conda\envs\libertem\lib\site-packages\IPython\sphinxext\ipython_console_highlighting.py
#   sphinx_issues (1.2.0) from c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx_issues.py
Traceback (most recent call last):
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\pybtex\style\formatting\__init__.py", line 67, in format_entry
    get_template = getattr(self, 'get_{}_template'.format(entry.type))
AttributeError: 'Style' object has no attribute 'get_dataset_template'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\application.py", line 348, in build
    self.builder.build_update()
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\builders\__init__.py", line 299, in build_update
    len(to_build))
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\builders\__init__.py", line 418, in read
    self._read_serial(docnames)
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\builders\__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\builders\__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\io.py", line 221, in read_doc
    pub.publish()
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\docutils\core.py", line 218, in publish
    self.apply_transforms()
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\docutils\core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinx\transforms\__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\docutils\transforms\__init__.py", line 172, in apply_transforms
    transform.apply(**kwargs)
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\sphinxcontrib\bibtex\transforms.py", line 99, in apply
    for entry in style.format_entries(entries):
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\pybtex\style\formatting\__init__.py", line 58, in format_entries
    yield self.format_entry(label, entry, bib_data=bib_data)
  File "c:\users\weber\.conda\envs\libertem\lib\site-packages\pybtex\style\formatting\__init__.py", line 69, in format_entry
    format_method = getattr(self, "format_" + entry.type)
AttributeError: 'Style' object has no attribute 'format_dataset'
```

**Comment by uellue** [comment]
It seems that `@dataset` is not a supported entry type in BibTeX. Unfortunately, Zenodo is generating entries of that type: https://zenodo.org/record/2566137/export/hx

**Comment by mcmtroffaes** [comment]
Thanks for reporting, and yes, there are many non-official custom style entries generated by various programs. I suggest writing a custom style that can handle entries of the dataset type. You'll need a template function called "format_dataset" to achieve this. You can see an example for customizing article entries here, which might provide a good starting point:

https://docs.pybtex.org/api/styles.html#template-language
