### ISSUE TITLE
BUG: KeyError: 'bibtex_foot_citation_refs'

### ISSUE THREAD

**Issue by drammock** [mcmtroffaes/sphinxcontrib-bibtex#223]
our CI build was working with 2.0.0, but is broken with 2.1.1:

```
Traceback (most recent call last):
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/circleci/.local/lib/python3.8/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/circleci/.local/lib/python3.8/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/home/circleci/.local/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinxcontrib/bibtex/foot_transforms.py", line 47, in apply
    for key in self.env.temp_data[
KeyError: 'bibtex_foot_citation_refs'
```

Without having carefully reviewed the code changes in 2.1 (but having read the issue/PR threads), I'd guess it's because we don't use any global citations in our website; everything is a local `footcite` with corresponding local `footbibliography`, plus one page that just does: 

```
.. bibliography:: ./references.bib
   :all:
   :list: enumerated
```

**Comment by mcmtroffaes** [comment]
Thanks for reporting, I'll get on this ASAP.

**Comment by mcmtroffaes** [comment]
This should now be fixed with the latest release. Thanks again for the quick report and the help with testing!
