### ISSUE TITLE
domain.py, line 389: ValueError: 'my_page' is not in list

### ISSUE THREAD

**Issue by VincentRouvreau** [mcmtroffaes/sphinxcontrib-bibtex#228]
Hello and thank you for this great extension !

Since an update of my CI (I did not find exactly when it happens, but the investigation is still in progress), I have this exception that is raised when sphinx-build:
```
Extension error:
Handler <function env_updated at 0x7efd64fea820> for event 'env-updated' threw an exception (exception: 'alpha_complex_user' is not in list)
```

So I launched sphinx-build in debug mode (`sphinx-build -P -b html /my/path/to/doc /my/path/to/destination`), and the full trace is:
```
Traceback (most recent call last):
  File "/builds/.local/lib/python3.8/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/builds/.local/lib/python3.8/site-packages/sphinxcontrib/bibtex/domain.py", line 204, in env_updated
    return domain.env_updated()
  File "/builds/.local/lib/python3.8/site-packages/sphinxcontrib/bibtex/domain.py", line 311, in env_updated
    for formatted_entry in self.get_formatted_entries(
  File "/builds/.local/lib/python3.8/site-packages/sphinxcontrib/bibtex/domain.py", line 455, in get_formatted_entries
    entries = dict(
  File "/builds/.local/lib/python3.8/site-packages/sphinxcontrib/bibtex/domain.py", line 437, in get_sorted_entries
    for key in self.get_all_cited_keys(docnames):
  File "/builds/.local/lib/python3.8/site-packages/sphinxcontrib/bibtex/domain.py", line 388, in get_all_cited_keys
    for citation_ref in sorted(
  File "/builds/.local/lib/python3.8/site-packages/sphinxcontrib/bibtex/domain.py", line 389, in <lambda>
    self.citation_refs, key=lambda c: docnames.index(c.docname)):
ValueError: 'alpha_complex_user' is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/builds/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/builds/.local/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/builds/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/builds/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/builds/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 423, in read
    for retval in self.events.emit('env-updated', self.env):
  File "/builds/.local/lib/python3.8/site-packages/sphinx/events.py", line 117, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function env_updated at 0x7f36bc9ee8b0> for event 'env-updated' threw an exception (exception: 'alpha_complex_user' is not in list)
> /builds/.local/lib/python3.8/site-packages/sphinx/events.py(117)emit()
-> raise ExtensionError(__("Handler %r for event %r threw an exception") %
```

It is not easy to reproduce as I have a lot of dependencies required to build the documentation (every optional third parties from this [installation page](https://gudhi.inria.fr/python/latest/installation.html)).
I must confess that there has been some tampering (especially to fix a sphinx warning saying a toctree is required, this is why I used `:orphan:` in my rst files, I also had to concatenate my biblio files into one, ... ).
I had a look in the documentation, but I could not find any debug section, any help would be appreciate.

**Comment by mcmtroffaes** [comment]
Thanks for reporting. The extension uses the toctree to determine the list of docnames in order, and it looks like that code might be missing some. The exception would likely happen if you had some documents in the build but not in any toctree. Anyway, it shouldn't be hard to fix the code to handle that edge case.

Is the code for your build somewhere publicly available, so that I can reproduce the error? That would help confirm the problem and aid adding a regression test for it, along with a fix of course.

**Comment by mcmtroffaes** [comment]
... is it this? https://github.com/GUDHI/gudhi-devel/tree/master/src/python/doc

**Comment by VincentRouvreau** [comment]
Yes that's it. It is a bit tricky as CMake is generating some python files but it is just that you have to install a lot of third parties to be able to generate the documentation

**Comment by mcmtroffaes** [comment]
Thanks, I managed to reproduce the bug without running cmake. The current develop branch might fix it. Is it possible for you to try it out?

**Comment by VincentRouvreau** [comment]
I just tested it and it works perfectly !
Thank you and have a good day.

**Comment by mcmtroffaes** [comment]
Great, thanks for confirming. Just need to add a test for this to the test suite, I'll then do a quick hotfix release, probably tomorrow.

**Comment by mcmtroffaes** [comment]
And regression test is working. Will do the hotfix release in the next 24 hours. Thanks again for the report and for helping with the test!
