### ISSUE TITLE
allow build to resume with a warning on missing bib field

### ISSUE THREAD

**Issue by Zac-HD** [mcmtroffaes/sphinxcontrib-bibtex#235]
Consider the following tiny project, which can be built with `sphinx-build . _build -ET`:

```python
# conf.py
extensions = ["sphinxcontrib.bibtex"]
bibtex_bibfiles = ["refs.bib"]
```
```rst
# index.rst

See :cite:`1987:nelson`.

.. bibliography::
```
```bibtex
# refs.bib
@book{1987:nelson,
  author    = {Edward Nelson},
  title     = {Radically Elementary Probability Theory},
  publisher = {Princeton University Press},
  year      = {1987}
}
```

If the key for the `:cite:` directive is not in the `.bib` file, Sphinx degrades gracefully by emitting a warning and leaving the key in the output text.  

However, if you delete the `year` line from the reference file, an unhandled exception is raised from `pybtex` and document compilation stops entirely.  The traceback:

```python-traceback
$ sphinx-build . _build -ET
Running Sphinx v3.2.1
checking for paper/refs.bib in bibtex cache... not found
parsing bibtex file paper/refs.bib... parsed 1 entries
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index

Traceback (most recent call last):
  File "site-packages/pybtex/database/__init__.py", line 496, in _find_field
    return self.fields[name]
  File "site-packages/pybtex/utils.py", line 163, in __getitem__
    return self._dict[key.lower()]
KeyError: 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/pybtex/database/__init__.py", line 499, in _find_field
    return self._find_person_field(name)
  File "site-packages/pybtex/database/__init__.py", line 471, in _find_person_field
    persons = self.persons[role]
  File "site-packages/pybtex/utils.py", line 163, in __getitem__
    return self._dict[key.lower()]
KeyError: 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/pybtex/style/template.py", line 261, in field
    field = entry._find_field(name, bib_data=context.get('bib_data'))
  File "site-packages/pybtex/database/__init__.py", line 501, in _find_field
    return self._find_crossref_field(name, bib_data)
  File "site-packages/pybtex/database/__init__.py", line 476, in _find_crossref_field
    raise KeyError(name)
KeyError: 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "site-packages/sphinxcontrib/bibtex/domain.py", line 208, in env_updated
    return domain.env_updated()
  File "site-packages/sphinxcontrib/bibtex/domain.py", line 316, in env_updated
    bibliography_key, docnames):
  File "site-packages/pybtex/style/formatting/__init__.py", line 58, in format_entries
    yield self.format_entry(label, entry, bib_data=bib_data)
  File "site-packages/pybtex/style/formatting/__init__.py", line 72, in format_entry
    text = get_template(entry).format_data(context)
  File "site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "site-packages/pybtex/style/formatting/__init__.py", line 32, in toplevel
    return join(sep=Symbol('newblock')) [children].format_data(data)
  File "site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "site-packages/pybtex/style/template.py", line 176, in join
    parts = [part for part in _format_list(children, data) if part]
  File "site-packages/pybtex/style/template.py", line 176, in <listcomp>
    parts = [part for part in _format_list(children, data) if part]
  File "site-packages/pybtex/style/template.py", line 150, in <genexpr>
    return (_format_data(part, data) for part in list_)
  File "site-packages/pybtex/style/template.py", line 146, in _format_data
    return f(data)
  File "site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "site-packages/pybtex/style/template.py", line 237, in sentence
    text = join(sep) [children].format_data(data)
  File "site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "site-packages/pybtex/style/template.py", line 176, in join
    parts = [part for part in _format_list(children, data) if part]
  File "site-packages/pybtex/style/template.py", line 176, in <listcomp>
    parts = [part for part in _format_list(children, data) if part]
  File "site-packages/pybtex/style/template.py", line 150, in <genexpr>
    return (_format_data(part, data) for part in list_)
  File "site-packages/pybtex/style/template.py", line 146, in _format_data
    return f(data)
  File "site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "site-packages/pybtex/style/template.py", line 189, in words
    return join(sep) [children].format_data(data)
  File "site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "site-packages/pybtex/style/template.py", line 176, in join
    parts = [part for part in _format_list(children, data) if part]
  File "site-packages/pybtex/style/template.py", line 176, in <listcomp>
    parts = [part for part in _format_list(children, data) if part]
  File "site-packages/pybtex/style/template.py", line 150, in <genexpr>
    return (_format_data(part, data) for part in list_)
  File "site-packages/pybtex/style/template.py", line 146, in _format_data
    return f(data)
  File "site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "site-packages/pybtex/style/template.py", line 265, in field
    raise FieldIsMissing(name, entry)
pybtex.style.template.FieldIsMissing: missing year in 1987:nelson

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "site-packages/sphinx/builders/__init__.py", line 424, in read
    for retval in self.events.emit('env-updated', self.env):
  File "site-packages/sphinx/events.py", line 118, in emit
    (listener.handler, name), exc) from exc
sphinx.errors.ExtensionError:
    Handler <function env_updated at 0x0000014F82D3FEA0> for event 'env-updated' 
    threw an exception (exception: missing year in 1987:nelson)

Extension error:
Handler <function env_updated at 0x0000014F82D3FEA0> for event 'env-updated' 
threw an exception (exception: missing year in 1987:nelson)
```

This is far from the only way that a subtly invalid bibtex file can cause internal errors (or has for me); merely the simplest to demonstrate here.  While discovering that my bibtex file is invalid is indeed useful and I always fix it ASAP, it would be much more convenient to find out via a warning than a crash.

Finally, thanks for `sphinxcontrib-bibtex` 😍 - it's made drafting and [sharing](https://zhd.dev/phd/) papers about Python code a lot more fun!

**Comment by mcmtroffaes** [comment]
You're welcome, and thanks for enquiring about this.

Exceptions are generally raised on unrecoverable errors, and in this case pybtex cannot format the entry as the year is missing, with no way to recover from that, so it raises an exception. The final line in your trace says "missing year in 1987:nelson" which points you exactly to the problem. Why is that, as you say, inconvenient?

**Comment by drammock** [comment]
For what it's worth, I sympathize with @Zac-HD here: if a similar minimal example were run through `pdflatex` and `bibtex` you would get a warning (`LaTeX Warning: Citation `1987:nelson' on page 1 undefined on input line 4.
` or similar), but the document would compile.  It's not unreasonable to want a similar level of graceful degradation from pybtex.

**Comment by mcmtroffaes** [comment]
I understand that, however the pybtex formatting system does not have a way to propagate warnings other than raising an exception. This is no different from using pybtex in lieu of bibtex for your latex compilations, and it's not something that can be resolved in this extension, except for completely omitting all entry text and emitting a warning (instead of more gracefully say replacing the year by question marks and emitting a warning).

**Comment by drammock** [comment]
> it's not something that can be resolved in this extension, except for completely omitting all entry text and emitting a warning

This doesn't sound that bad to me, actually. But really I only meant to say "I agree that crashing is inconvenient compared to completing with warnings", mostly because if each build takes a few minutes and there are multiple problems, it would be nice for the run to finish and to see all problems at once (as warnings), instead of seeing one problem at a time (as errors) and having to re-build after each fix.

**Comment by mcmtroffaes** [comment]
That's a very valid point @drammock - I'll see what I can do on that front.

**Comment by Zac-HD** [comment]
Another motivation is that warnings work well with [`sphinx-autobuild`](https://pypi.org/project/sphinx-autobuild/), whereas unhandled exceptions put it in an unrecoverable error state where even ctrl-C does nothing!

**Comment by mcmtroffaes** [comment]
This should now work on develop. Could you give it a quick spin to see if this works for you?

**Comment by Zac-HD** [comment]
Just tried it out; and it works beautifully :-)  Thanks!

**Comment by mcmtroffaes** [comment]
Lovely, thanks for testing and confirming!
