### ISSUE TITLE
sphinx warnings when building docs

### ISSUE THREAD

**Issue by kloczek** [mcmtroffaes/sphinxcontrib-bibtex#270]
Looks like sphonx now shows some warnings
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.1.2
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from http://www.sphinx-doc.org/en/master/objects.inv...
intersphinx inventory has moved: http://www.sphinx-doc.org/en/master/objects.inv -> https://www.sphinx-doc.org/en/master/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 17 added, 0 changed, 0 removed
reading sources... [100%] usage
WARNING: autodoc: failed to import class 'FootBibtexDomain' from module 'sphinxcontrib.bibtex.foot_domain'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'sphinxcontrib.bibtex.foot_domain' has no attribute 'FootBibtexDomain'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 332, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2729, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 433, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: FootBibtexDomain

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-sphinxcontrib-bibtex.3 { quickstart usage api api/interface api/roles api/nodes api/directives api/transforms api/domains api/bibfile api/referencing api/plugin api/pybtex changes license related } done
build succeeded, 1 warning.
```

**Comment by mcmtroffaes** [comment]
I fear I can't reproduce, it works for me locally (see logs below). ``FootBibtexDomain`` is a recent addition. My first guess would be that the installed version of the library might be older than the docs you're building?

---

Build logs:

```
$ make man
sphinx-build -b man -d _build/doctrees   . _build/man
Running Sphinx v4.0.3
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from http://www.sphinx-doc.org/en/master/objects.inv...
intersphinx inventory has moved: http://www.sphinx-doc.org/en/master/objects.inv -> https://www.sphinx-doc.org/en/master/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 17 added, 0 changed, 0 removed
reading sources... [100%] usage
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... sphinxcontrib-bibtex.1 { quickstart usage api api/interface api/roles api/nodes api/directives api/transforms api/domains api/bibfile api/referencing api/plugin api/pybtex changes license related } done
build succeeded.

The manual pages are in _build/man.

Build finished. The manual pages are in _build/man.
```

**Comment by kloczek** [comment]
You are using sphinx 4.0.3.
In my output you can see that I'm using 4.1.2.

**Comment by mcmtroffaes** [comment]
Can't reproduce with 4.1.2 either:

```
$ make man
sphinx-build -b man -d _build/doctrees   . _build/man
Running Sphinx v4.1.2
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from http://www.sphinx-doc.org/en/master/objects.inv...
intersphinx inventory has moved: http://www.sphinx-doc.org/en/master/objects.inv -> https://www.sphinx-doc.org/en/master/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 17 added, 0 changed, 0 removed
reading sources... [100%] usage
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... sphinxcontrib-bibtex.1 { quickstart usage api api/interface api/roles api/nodes api/directives api/transforms api/domains api/bibfile api/referencing api/plugin api/pybtex changes license related } done
build succeeded.

The manual pages are in _build/man.

Build finished. The manual pages are in _build/man.
```

**Comment by mcmtroffaes** [comment]
Closing due to inactivity and inability to reproduce.
