### ISSUE TITLE
Crossref does not seem to work

### ISSUE THREAD

**Issue by vnmabus** [mcmtroffaes/sphinxcontrib-bibtex#325]
I am trying to add individual chapters of a book and use a crossref field to link them with the original book:
```bibtex
@inbook{srivastava+klassen_2016_functionala,
  crossref = {srivastava+klassen_2016_functional},
  title = {Functional Data and Elastic Registration},
  pages = {73--123},
}

@inbook{srivastava+klassen_2016_statistical,
  crossref = {srivastava+klassen_2016_functional},
  title = {Statistical Modeling of Functional Data},
  pages = {269--303},
}

@book{srivastava+klassen_2016_functional,
  title = {Functional and Shape Data Analysis},
  booktitle = {Functional and Shape Data Analysis},
  author = {Srivastava, Anuj and Klassen, Eric P.},
  editor = {Bicke, Peter and Diggle, Peter and Fienberg, Stephen E. and Gather, Ursula and Olkin, Ingram and Zeger, Scott},
  year = {2016},
  series = {Springer {{Series}} in {{Statistics}}},
  publisher = {{Springer-Verlag}},
  address = {{New York}},
  doi = {10.1007/978-1-4939-4020-2},
  url = {https://www.springer.com/gp/book/9781493940189},
  urldate = {2020-01-12},
  isbn = {978-1-4939-4018-9},
  langid = {english}
}
```

However, this does not seem to work. I obtain the following error:
```python
Ha ocurrido una excepción:
  File "<my_path>/site-packages/pybtex/style/template.py", line 281, in names
    raise FieldIsMissing(role, context['entry'])
pybtex.style.template.FieldIsMissing: missing editor in srivastava+klassen_2016_functionala
```

The complete traceback is:
<details>

```python
Traceback (most recent call last):
  File "<my_path>/site-packages/pybtex/style/template.py", line 279, in names
    persons = context['entry'].persons[role]
  File "<my_path>/site-packages/pybtex/utils.py", line 163, in __getitem__
    return self._dict[key.lower()]
KeyError: 'editor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<my_path>/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "<my_path>/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "<my_path>/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "<my_path>/site-packages/sphinx/builders/__init__.py", line 327, in build
    updated_docnames = set(self.read())
  File "<my_path>/site-packages/sphinx/builders/__init__.py", line 434, in read
    self._read_serial(docnames)
  File "<my_path>/site-packages/sphinx/builders/__init__.py", line 455, in _read_serial
    self.read_doc(docname)
  File "<my_path>/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    publisher.publish()
  File "<my_path>/site-packages/docutils/core.py", line 224, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "<my_path>/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "<my_path>/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "<my_path>/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "<my_path>/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "<my_path>/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "<my_path>/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "<my_path>/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 2799, in text
    paragraph, literalnext = self.paragraph(lines, startline)
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 416, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 425, in inline_text
    nodes, messages = self.inliner.parse(text, lineno,
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 649, in parse
    before, inlines, remaining, sysmessages = method(self, match,
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 792, in interpreted_or_phrase_ref
    nodelist, messages = self.interpreted(rawsource, escaped, role,
  File "<my_path>/site-packages/docutils/parsers/rst/states.py", line 889, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "<my_path>/site-packages/sphinx/domains/__init__.py", line 267, in role_adapter
    return self.roles[name](fullname, rawtext, text, lineno,
  File "<my_path>/site-packages/sphinx/util/docutils.py", line 535, in __call__
    return super().__call__(name, rawtext, text, lineno, inliner, options, content)
  File "<my_path>/site-packages/sphinx/util/docutils.py", line 476, in __call__
    return self.run()
  File "<my_path>/site-packages/sphinx/roles.py", line 106, in run
    return self.create_xref_node()
  File "<my_path>/site-packages/sphinx/roles.py", line 140, in create_xref_node
    return self.result_nodes(self.inliner.document, self.env, refnode, is_ref=True)
  File "<my_path>/site-packages/sphinxcontrib/bibtex/foot_roles.py", line 71, in result_nodes
    formatted_entry = style.format_entry(label='', entry=entry)
  File "<my_path>/site-packages/pybtex/style/formatting/__init__.py", line 72, in format_entry
    text = get_template(entry).format_data(context)
  File "<my_path>/site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "<my_path>/site-packages/pybtex/style/formatting/__init__.py", line 32, in toplevel
    return join(sep=Symbol('newblock')) [children].format_data(data)
  File "<my_path>/site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "<my_path>/site-packages/pybtex/style/template.py", line 176, in join
    parts = [part for part in _format_list(children, data) if part]
  File "<my_path>/site-packages/pybtex/style/template.py", line 176, in <listcomp>
    parts = [part for part in _format_list(children, data) if part]
  File "<my_path>/site-packages/pybtex/style/template.py", line 150, in <genexpr>
    return (_format_data(part, data) for part in list_)
  File "<my_path>/site-packages/pybtex/style/template.py", line 146, in _format_data
    return f(data)
  File "<my_path>/site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "<my_path>/site-packages/pybtex/style/template.py", line 345, in first_of
    for child in _format_list(children, data):
  File "<my_path>/site-packages/pybtex/style/template.py", line 150, in <genexpr>
    return (_format_data(part, data) for part in list_)
  File "<my_path>/site-packages/pybtex/style/template.py", line 146, in _format_data
    return f(data)
  File "<my_path>/site-packages/pybtex/style/template.py", line 130, in format_data
    return self.f(self.children, data, *self.args, **self.kwargs)
  File "<my_path>/site-packages/pybtex/style/template.py", line 281, in names
    raise FieldIsMissing(role, context['entry'])
pybtex.style.template.FieldIsMissing: missing editor in srivastava+klassen_2016_functionala
```

</details>

**Comment by mcmtroffaes** [comment]
Thanks for reporting. This seems to be an issue with pybtex rather than sphinxcontrib-bibtex; but as far as I know crossrefs should work... I'll need to try to step this through the debugger to see why it's not working in your case.

**Comment by mcmtroffaes** [comment]
Apologies for the time it's gotten me to diagnose this properly. This is indeed a bug in pybtex and not with sphinxcontrib-bibtex. I've reported it upstream along with my analysis of where the problem is:

https://bitbucket.org/pybtex-devs/pybtex/issues/441/author-editor-fields-not-resolved-via
