### ISSUE TITLE
Error installing via pip

### ISSUE THREAD

**Issue by Hibou57** [mcmtroffaes/sphinxcontrib-bibtex#73]
I get an error installing via pip. Sorry for posting the unfriendly logs as‑is, I don't know how to attach a file here.

```
install --install-option="--prefix= <dir>/sphinx" sphinxcontrib-bibtex                                                 ~
Downloading/unpacking sphinxcontrib-bibtex
  Downloading sphinxcontrib_bibtex-0.3.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): Sphinx>=1.0 in ./apps/python3/lib/python3.4/site-packages (from sphinxcontrib-bibtex)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in ./apps/python3/lib/python3.4/site-packages (from sphinxcontrib-bibtex)
Downloading/unpacking latexcodec>=0.3.0 (from sphinxcontrib-bibtex)
  Downloading latexcodec-1.0.0-py2.py3-none-any.whl
Downloading/unpacking pybtex>=0.17 (from sphinxcontrib-bibtex)
  Downloading pybtex-0.18.tar.bz2 (256kB): 256kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File " <dir>/python3/lib/python3.4/tarfile.py", line 1640, in bz2open
    import bz2
  File " <dir>/python3/lib/python3.4/bz2.py", line 20, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ImportError: No module named '_bz2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File " <dir>/python3/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File " <dir>/python3/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File " <dir>/python3/lib/python3.4/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File " <dir>/python3/lib/python3.4/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File " <dir>/python3/lib/python3.4/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File " <dir>/python3/lib/python3.4/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File " <dir>/python3/lib/python3.4/site-packages/pip/util.py", line 543, in untar_file
    tar = tarfile.open(filename, mode)
  File " <dir>/python3/lib/python3.4/tarfile.py", line 1565, in open
    return func(name, filemode, fileobj, **kwargs)
  File " <dir>/python3/lib/python3.4/tarfile.py", line 1642, in bz2open
    raise CompressionError("bz2 module is not available")
tarfile.CompressionError: bz2 module is not available

Storing debug log for failure in <home>/.pip/pip.log
```

What's in `<home>/.pip/pip.log`:

```
------------------------------------------------------------
 <dir>/python3/bin/pip3 run on Sun Aug 17 08:46:30 2014
Downloading/unpacking sphinxcontrib-bibtex
  Getting page https://pypi.python.org/simple/sphinxcontrib-bibtex/
  URLs to search for versions for sphinxcontrib-bibtex:
  * https://pypi.python.org/simple/sphinxcontrib-bibtex/
  Analyzing links from page https://pypi.python.org/simple/sphinxcontrib-bibtex/
    Found link https://pypi.python.org/packages/2.7/s/sphinxcontrib-bibtex/sphinxcontrib_bibtex-0.3.0-py2.py3-none-any.whl#md5=0b114b6a5507b3d3df9bd3dc58225717 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.3.0
    Found link https://pypi.python.org/packages/2.7/s/sphinxcontrib-bibtex/sphinxcontrib_bibtex-0.3.1-py2.py3-none-any.whl#md5=804c4bc2a7f09e57ce422f25e375e371 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.1.tar.gz#md5=53778d8b5f865c9451fbe2a907904c8b (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.1
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.2.zip#md5=8cc9499198ba2f8e23f49cb9172a4d09 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.2
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.3.zip#md5=d85e546e2a9df2f1402d11c25a755ce6 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.3
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.4.zip#md5=c6e8e0114b337aa5b755f143fe095125 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.4
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.5.zip#md5=6ca018bf02ffae31f1543ee0e674edce (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.5
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.6.zip#md5=9267bee1d53fe3c429d88b7203f05224 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.6
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.7.zip#md5=75b516d168f2682c22d1f4a898a34551 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.7
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.8.zip#md5=98a097a66da52203c8a21b931c5677e7 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.8
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.2.9.zip#md5=d529f94c0d0277a3c7080748b7c17bcf (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.2.9
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.3.0.tar.gz#md5=05218cd42b3ecf8ffbe3191c38596fed (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.3.0
    Found link https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.3.1.tar.gz#md5=e7d5807297c71a6281ab5ee66293e339 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/), version: 0.3.1
  Using version 0.3.1 (newest of versions: 0.3.1, 0.3.1, 0.3.0, 0.3.0, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1)
  Downloading sphinxcontrib_bibtex-0.3.1-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/2.7/s/sphinxcontrib-bibtex/sphinxcontrib_bibtex-0.3.1-py2.py3-none-any.whl#md5=804c4bc2a7f09e57ce422f25e375e371 (from https://pypi.python.org/simple/sphinxcontrib-bibtex/)
Requirement already satisfied (use --upgrade to upgrade): Sphinx>=1.0 in ./apps/python3/lib/python3.4/site-packages (from sphinxcontrib-bibtex)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in ./apps/python3/lib/python3.4/site-packages (from sphinxcontrib-bibtex)
Downloading/unpacking latexcodec>=0.3.0 (from sphinxcontrib-bibtex)
  Getting page https://pypi.python.org/simple/latexcodec/
  URLs to search for versions for latexcodec>=0.3.0 (from sphinxcontrib-bibtex):
  * https://pypi.python.org/simple/latexcodec/
  Analyzing links from page https://pypi.python.org/simple/latexcodec/
    Found link https://pypi.python.org/packages/2.7/l/latexcodec/latexcodec-0.3.2-py2.py3-none-any.whl#md5=8d7fb2db759f4ab626d533c4544d97b2 (from https://pypi.python.org/simple/latexcodec/), version: 0.3.2
    Found link https://pypi.python.org/packages/2.7/l/latexcodec/latexcodec-1.0.0-py2.py3-none-any.whl#md5=5e52261f9a176eda02cd3b10c8054dae (from https://pypi.python.org/simple/latexcodec/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-0.1.tar.gz#md5=cb7100c1810055c23bf8a37a345d23d8 (from https://pypi.python.org/simple/latexcodec/), version: 0.1
    Found link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-0.2.tar.gz#md5=857d3f6da1e27b72c68d952396b59ae4 (from https://pypi.python.org/simple/latexcodec/), version: 0.2
    Found link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-0.3.0.zip#md5=e4c21c60c3dd555fbae6807b21c4e0c5 (from https://pypi.python.org/simple/latexcodec/), version: 0.3.0
    Found link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-0.3.1.zip#md5=3a48cb479640e1080b83e716c26231a5 (from https://pypi.python.org/simple/latexcodec/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-0.3.2.tar.gz#md5=08f732d02cdde0c31bbf8a8e58b9ed5a (from https://pypi.python.org/simple/latexcodec/), version: 0.3.2
    Found link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-1.0.0.tar.gz#md5=932c0910914ac274ee4293c27027e0d4 (from https://pypi.python.org/simple/latexcodec/), version: 1.0.0
  Ignoring link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-0.1.tar.gz#md5=cb7100c1810055c23bf8a37a345d23d8 (from https://pypi.python.org/simple/latexcodec/), version 0.1 doesn't match >=0.3.0
  Ignoring link https://pypi.python.org/packages/source/l/latexcodec/latexcodec-0.2.tar.gz#md5=857d3f6da1e27b72c68d952396b59ae4 (from https://pypi.python.org/simple/latexcodec/), version 0.2 doesn't match >=0.3.0
  Using version 1.0.0 (newest of versions: 1.0.0, 1.0.0, 0.3.2, 0.3.2, 0.3.1, 0.3.0)
  Downloading latexcodec-1.0.0-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/2.7/l/latexcodec/latexcodec-1.0.0-py2.py3-none-any.whl#md5=5e52261f9a176eda02cd3b10c8054dae (from https://pypi.python.org/simple/latexcodec/)
Downloading/unpacking pybtex>=0.17 (from sphinxcontrib-bibtex)
  Getting page https://pypi.python.org/simple/pybtex/
  URLs to search for versions for pybtex>=0.17 (from sphinxcontrib-bibtex):
  * https://pypi.python.org/simple/pybtex/
  Analyzing links from page https://pypi.python.org/simple/pybtex/
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.10.tar.bz2#md5=3b7a6f1015a3de284e043afe9fd0f6d2 (from https://pypi.python.org/simple/pybtex/), version: 0.10
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.11.tar.bz2#md5=c15c8c326a77af4e2863500cd33fbf60 (from https://pypi.python.org/simple/pybtex/), version: 0.11
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.12.tar.bz2#md5=e35448aac7d20684e11225f2d42f6e9e (from https://pypi.python.org/simple/pybtex/), version: 0.12
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.13.1.tar.bz2#md5=7e9e244d0125abe4cdc1f180ada348dd (from https://pypi.python.org/simple/pybtex/), version: 0.13.1
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.13.2.tar.bz2#md5=812195385bc242376b8263aa77390082 (from https://pypi.python.org/simple/pybtex/), version: 0.13.2
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.14.1.tar.bz2#md5=67b399d3c8269fa89c53c67e01b86e6a (from https://pypi.python.org/simple/pybtex/), version: 0.14.1
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.14.tar.bz2#md5=357687821cebca2d4943c5ad0441bd47 (from https://pypi.python.org/simple/pybtex/), version: 0.14
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.15.tar.bz2#md5=5f1e1564859c6db84bd0cfb2d39539cc (from https://pypi.python.org/simple/pybtex/), version: 0.15
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.16.tar.bz2#md5=951c4f913fb9c20362ece9cdf7cb3a3c (from https://pypi.python.org/simple/pybtex/), version: 0.16
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.17.tar.bz2#md5=03d9a194e410cf0637cf4ffff48c910f (from https://pypi.python.org/simple/pybtex/), version: 0.17
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.17.tar.gz#md5=732d0bf90da23c28084acd57404fe8b3 (from https://pypi.python.org/simple/pybtex/), version: 0.17
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.18.tar.bz2#md5=306457c18eb861ec3f644a7e2df98ae4 (from https://pypi.python.org/simple/pybtex/), version: 0.18
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.18.tar.gz#md5=f58ade6d487424a4a10612cb08bba5ce (from https://pypi.python.org/simple/pybtex/), version: 0.18
    Found link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.9.tar.bz2#md5=820d5b3a7875d4516bef86cf830d8b8f (from https://pypi.python.org/simple/pybtex/), version: 0.9
    Skipping link http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/); not a file
    Skipping link https://code.launchpad.net/%7eero-sennin/pybtex/trunk (from https://pypi.python.org/simple/pybtex/); not a file
    Skipping link https://code.launchpad.net/%7epybtex-devs/pybtex/trunk (from https://pypi.python.org/simple/pybtex/); not a file
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Not searching http://pybtex.sourceforge.net/ (from https://pypi.python.org/simple/pybtex/) for files because external urls are disallowed.
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.10.tar.bz2#md5=3b7a6f1015a3de284e043afe9fd0f6d2 (from https://pypi.python.org/simple/pybtex/), version 0.10 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.11.tar.bz2#md5=c15c8c326a77af4e2863500cd33fbf60 (from https://pypi.python.org/simple/pybtex/), version 0.11 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.12.tar.bz2#md5=e35448aac7d20684e11225f2d42f6e9e (from https://pypi.python.org/simple/pybtex/), version 0.12 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.13.1.tar.bz2#md5=7e9e244d0125abe4cdc1f180ada348dd (from https://pypi.python.org/simple/pybtex/), version 0.13.1 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.13.2.tar.bz2#md5=812195385bc242376b8263aa77390082 (from https://pypi.python.org/simple/pybtex/), version 0.13.2 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.14.1.tar.bz2#md5=67b399d3c8269fa89c53c67e01b86e6a (from https://pypi.python.org/simple/pybtex/), version 0.14.1 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.14.tar.bz2#md5=357687821cebca2d4943c5ad0441bd47 (from https://pypi.python.org/simple/pybtex/), version 0.14 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.15.tar.bz2#md5=5f1e1564859c6db84bd0cfb2d39539cc (from https://pypi.python.org/simple/pybtex/), version 0.15 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.16.tar.bz2#md5=951c4f913fb9c20362ece9cdf7cb3a3c (from https://pypi.python.org/simple/pybtex/), version 0.16 doesn't match >=0.17
  Ignoring link https://pypi.python.org/packages/source/p/pybtex/pybtex-0.9.tar.bz2#md5=820d5b3a7875d4516bef86cf830d8b8f (from https://pypi.python.org/simple/pybtex/), version 0.9 doesn't match >=0.17
  Using version 0.18 (newest of versions: 0.18, 0.18, 0.17, 0.17)
  Downloading from URL https://pypi.python.org/packages/source/p/pybtex/pybtex-0.18.tar.bz2#md5=306457c18eb861ec3f644a7e2df98ae4 (from https://pypi.python.org/simple/pybtex/)
Cleaning up...
  Removing temporary dir /tmp/pip_build_<user>...
Exception:
Traceback (most recent call last):
  File " <dir>/python3/lib/python3.4/tarfile.py", line 1640, in bz2open
    import bz2
  File " <dir>/python3/lib/python3.4/bz2.py", line 20, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ImportError: No module named '_bz2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File " <dir>/python3/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File " <dir>/python3/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File " <dir>/python3/lib/python3.4/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File " <dir>/python3/lib/python3.4/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File " <dir>/python3/lib/python3.4/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File " <dir>/python3/lib/python3.4/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File " <dir>/python3/lib/python3.4/site-packages/pip/util.py", line 543, in untar_file
    tar = tarfile.open(filename, mode)
  File " <dir>/python3/lib/python3.4/tarfile.py", line 1565, in open
    return func(name, filemode, fileobj, **kwargs)
  File " <dir>/python3/lib/python3.4/tarfile.py", line 1642, in bz2open
    raise CompressionError("bz2 module is not available")
tarfile.CompressionError: bz2 module is not available
```

**Comment by miguel5** [comment]
This worked!
