### ISSUE TITLE
A reference with no author field make it crash

### ISSUE THREAD

**Issue by mickours** [mcmtroffaes/sphinxcontrib-bibtex#85]
Hi,

When I try to use the ``:cite:`` tag to reference a Web page with no author sphinx crash.
If I add a non empty author field on the bibtex it works fine.

Here is the bibtex:
```
@misc{_software_2015,
	title = {Software projects built on {Mesos}},
	url = {http://mesos.apache.org/documentation/latest/mesos-frameworks/},
	urldate = {2015-09-18},
	month = sep,
	year = {2015},
}
```

And the full error report:
```
# Sphinx version: 1.3.1
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   2 added, 0 changed, 0 removed
#   reading sources... [ 50%] Report
#   checking for /home/mercierm/SparkleShare/thesis/bibtex/bibli.bib in bibtex cache...
#   not found
#   parsing bibtex file /home/mercierm/SparkleShare/thesis/bibtex/bibli.bib...
#   parsed 53 entries
#   checking for /home/mercierm/SparkleShare/thesis/bibtex/manual_ref.bib in bibtex cache...
#   not found
#   parsing bibtex file /home/mercierm/SparkleShare/thesis/bibtex/manual_ref.bib...
#   parsed 2 entries
# Loaded extensions:
#   alabaster (0.7.6) from /usr/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinxcontrib.bibtex (unknown version) from /usr/lib/python3.4/site-packages/sphinxcontrib/bibtex/__init__.py
#   sphinx.ext.ifconfig (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.todo (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/todo.py
#   sphinx.ext.mathjax (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/mathjax.py
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/usr/lib/python3.4/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/usr/lib/python3.4/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib/python3.4/site-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/usr/lib/python3.4/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/usr/lib/python3.4/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3.4/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.4/site-packages/sphinxcontrib/bibtex/transforms.py", line 107, in apply
    for entry in style.format_entries(entries):
  File "/usr/lib/python3.4/site-packages/pybtex/style/formatting/__init__.py", line 49, in format_entries
    sorted_entries = self.sort(entries)
  File "/usr/lib/python3.4/site-packages/pybtex/style/sorting/__init__.py", line 34, in sort
    sorted_keys = sorted(entry_dict)
TypeError: unorderable types: NoneType() < str()
```

**Comment by mcmtroffaes** [comment]
Thanks for the report, and apologies for the slow response. This looks like a bug in pybtex, I'll chase it up upstream.

**Comment by mcmtroffaes** [comment]
... in the mean time if you provide a key for sorting, then I think pybtex should process it fine:

https://tex.stackexchange.com/questions/54441/bib-sorting-without-author

**Comment by mcmtroffaes** [comment]
Fix pushed upstream:

https://bitbucket.org/pybtex-devs/pybtex/pull-requests/1/sorting-keys-no-longer-return-none-fixes/diff

In the mean time you can work around it simply by using Python 2 - which does not complain when comparing None with a str.

**Comment by mcmtroffaes** [comment]
The fix has been merged upstream, so closing. Thanks again for reporting!

**Comment by mcmtroffaes** [comment]
A new version of pybtex has just been released yesterday, so this should now work with pypi's pybtex.
